!> \file clust.f90
!! \brief Hierarchical clustering driver for encounter arrays.
!!
!! clust.f90 - Hierarchical clustering for encounter arrays.
!!
!! Usage: ./clust -help
!!
!! Reads an array and runs hierarchical clustering with mean linkage. Results written to output_name files.
!!
!! @author Abraham Muñiz-Chicharro
!! @version 1.0
!! @date 2026-04-05
program main

  USE mod_array
  USE mod_clust_algorithm
  USE read_input

  implicit none

  ! High-level workflow:
  ! 1) Parse CLI options and validate required inputs.
  ! 2) Read encounter complexes metadata (transforms + headers).
  ! 3) Read the 1D array generated by make_data.
  ! 4) Run hierarchical clustering with mean linkage.
  ! 5) Write clustering outputs with basename given in -output_name.

    character*128 :: datadist_filename, complexes_filename
    character*128 :: output_name
    integer :: nb_encounters, tot_encounters
    type ( type_assoc_file ) :: complexes

    real (kind=8), dimension(:), allocatable :: array
    logical :: complexes_bool, nb_encounters_bool, help_bool
    logical :: output_name_bool
    integer :: detect_unit, detect_stat, nlines
    character(len=1) :: dummy

    call parse_arguments( &
      complexes_filename, complexes_bool, &
      nb_encounters, nb_encounters_bool, &
      datadist_filename, &
      output_name, output_name_bool, &
      help_bool)

    ! Help path exits before any heavy I/O or clustering work.
    if ( help_bool ) then
      call print_help()
      STOP 0
    end if

    ! Validate required options.
    if ( .not. complexes_bool ) then
      print *, '[clust] ERROR: Encounter complexes file not provided. Use -complexes <file>'
      print *, '[clust] For usage, run: ./clust -help'
      STOP 1
    end if

    if ( len_trim(datadist_filename) == 0 ) then
      print *, '[clust] ERROR: No input file provided. Use -input <file>'
      print *, '[clust] For usage, run: ./clust -help'
      STOP 1
    end if

    if ( .not. output_name_bool ) then
      print *, '[clust] ERROR: Output name not provided. Use -output_name <name>'
      print *, '[clust] For usage, run: ./clust -help'
      STOP 1
    end if

    ! Read encounter-complex records and transformation parameters.
    call read_assoc(complexes, complexes_filename, tot_encounters)

    ! Keep number of encounters inside available range.
    if ( nb_encounters .gt. tot_encounters ) then
      print *, '[clust] WARNING: -nb_encounters > available. Using all encounters in ', trim(complexes_filename)
      nb_encounters = tot_encounters
      print *, '[clust] Total encounters available: ', nb_encounters
    else if (.not. nb_encounters_bool) then
      print *, '[clust] WARNING: -nb_encounters not given. Using all available.'
      nb_encounters = tot_encounters
      print *, '[clust] If you want a specific number, use -nb_encounters <N>'
    end if

    ! Validate input format:
    ! - single line -> 1D array path
    ! - multiple lines -> unsupported multi-row input
    detect_unit = 99
    open(detect_unit, file=trim(datadist_filename), status='old', iostat=detect_stat)
    if (detect_stat /= 0) then
      print *, "ERROR. Cannot open input file: ", trim(datadist_filename)
      STOP 1
    end if
    nlines = 0
    do
      read(detect_unit, '(A)', iostat=detect_stat) dummy
      if (detect_stat /= 0) exit
      nlines = nlines + 1
    end do
    close(detect_unit)

    if (nlines == 0) then
      print *, "ERROR. Input file is empty: ", trim(datadist_filename)
      STOP 1
    else
      if (nlines > 1) then
        print *, "ERROR. Multi-row input is no longer supported: ", trim(datadist_filename)
        print *, "Please provide a single-line 1D array generated by make_data."
        STOP 1
      end if
      write(*,*) 'Detected input as 1D array'
    end if

    call read_array(array, nb_encounters, datadist_filename)
    call linkage_clustering(array, nb_encounters, output_name, complexes)

    contains
    !> Parse command-line arguments for `clust`.
    !!
    !! Parses all CLI flags and fills program configuration values.
    !! @param[out] p_complexes_filename Value parsed from `-complexes`
    !! @param[out] p_complexes_bool     Whether `-complexes` was provided
    !! @param[out] p_nb_encounters      Value parsed from `-nb_encounters`
    !! @param[out] p_nb_encounters_bool Whether `-nb_encounters` was provided
    !! @param[out] p_datadist_filename  Value parsed from `-input`
    !! @param[out] p_output_name        Value parsed from `-output_name`
    !! @param[out] p_output_name_bool   Whether `-output_name` was provided
    !! @param[out] p_help_bool          Whether `-help` was provided
    subroutine parse_arguments( &
      p_complexes_filename, p_complexes_bool, &
      p_nb_encounters, p_nb_encounters_bool, &
      p_datadist_filename, &
      p_output_name, p_output_name_bool, &
      p_help_bool)
      implicit none

      character*128, intent(out) :: p_complexes_filename
      logical, intent(out) :: p_complexes_bool
      integer, intent(out) :: p_nb_encounters
      logical, intent(out) :: p_nb_encounters_bool
      character*128, intent(out) :: p_datadist_filename
      character*128, intent(out) :: p_output_name
      logical, intent(out) :: p_output_name_bool
      logical, intent(out) :: p_help_bool

      integer :: nb_argument, count_arg, ios
      character*128 :: argument

      nb_argument = command_argument_count()
      if ( nb_argument == 0 ) then
        print *, '[clust] ERROR: No arguments parsed.'
        print *, '[clust] For usage, run: ./clust -help'
        call print_help()
        STOP 1
      end if

      p_nb_encounters = 0
      p_complexes_bool = .false.
      p_output_name_bool = .false.
      p_nb_encounters_bool = .false.
      p_help_bool = .false.
      p_datadist_filename = ''
      argument = ""
      count_arg = 1

      do while ( count_arg <= nb_argument )
        call getarg( count_arg, argument )

        if ( trim(argument) == "-complexes" ) then
          p_complexes_bool = .true.
          call getarg( count_arg+1, argument )
          p_complexes_filename = trim(argument)
          count_arg = count_arg + 1
        else if ( trim(argument) == "-nb_encounters" ) then
          p_nb_encounters_bool = .true.
          call getarg( count_arg+1, argument )
          read(argument, *, IOSTAT=ios) p_nb_encounters
          if (ios /= 0) then
            print *, "ERROR. Integer expected for the -nb_encounters argument."
          end if
          count_arg = count_arg + 1
        else if ( trim(argument) == "-input" ) then
          call getarg( count_arg+1, argument )
          p_datadist_filename = trim(argument)
          count_arg = count_arg + 1
        else if ( trim(argument) == "-output_name" ) then
          p_output_name_bool = .true.
          call getarg( count_arg+1, argument )
          p_output_name = trim(argument)
          count_arg = count_arg + 1
        else if ( trim(argument) == "-help" ) then
          p_help_bool = .true.
        else
          print *, '[clust] ERROR: Argument ''', trim(argument), ''' not recognized.'
          print *, '[clust] For usage, run: ./clust -help'
          STOP 1
        end if

        count_arg = count_arg + 1
      end do

    end subroutine parse_arguments

    !> Print usage and help information for the `clust` program.
    !!
    !! Describes command-line options and provides an example invocation.
    subroutine print_help()

      print *, ""
      print *, "This program performs hierarchical clustering on encounter complexes."
      print *, "It receives as inputs the encounter complexes file, array input file,"
      print *, "and clustering parameters. Mean linkage is used."
      print *, ""
      print *, "Usage:"
      print *, "  ./clust -complexes <file> -input <file> [OPTIONS]"
      print *, ""
      print *, "Required arguments:"
      print *, "  -complexes <file>       Encounter complexes file"
      print *, "  -input <file>           Input 1D array file"
      print *, "  -output_name <name>     Base name for output files"
      print *, ""
      print *, "Optional arguments:"
      print *, "  -nb_encounters <N>      Number of encounters to cluster"
      print *, "                          (default: all encounters in complexes file)"
      print *, "  -help                   Display this help message"
      print *, ""
      print *, "Input format:"
      print *, "  - 1 line  -> treated as a 1D array"
      print *, ""
      print *, "Example:"
      print *, "  ./clust -complexes assoc_complexes -input array_z.txt \\"
      print *, "          -nb_encounters 5000 -output_name Cu_z"
      print *, ""
      STOP
      
    end subroutine print_help
  
  end program main
