!> \file threshold.f90
!! \brief Threshold-based encounter selection from precomputed arrays.
!!
!! threshold.f90 - Filter encounters using an input array generated by make_data.
!!
!! Usage: ./threshold -help
!!
!! Reads a precomputed per-encounter array and the matching complexes file,
!! applies a cutoff, and writes filtered array values and filtered complexes.
!!
!! @author Abraham Muniz-Chicharro
!! @version 1.0
!! @date 2026-06-07
program main
  use read_input
  use mod_array, only: read_array
  use mod_threshold, only: sort_array

  implicit none

  character(len=128) :: array_input_filename
  character(len=128) :: complexes_filename
  character(len=128) :: output_complexes_filename
  character(len=128) :: datadist_filename
  logical :: array_input_bool
  logical :: complexes_bool
  logical :: output_complexes_bool
  logical :: array_bool
  logical :: cutoff_bool
  logical :: nb_encounters_bool
  logical :: help_bool
  real(kind=8) :: cutoff
  integer :: nb_encounters, tot_encounters, i
  type(type_assoc_file) :: complexes
  real(kind=8), allocatable, dimension(:) :: distarray
  integer, allocatable, dimension(:) :: encounter_indexes

  call parse_arguments( &
    array_input_filename, array_input_bool, &
    complexes_filename, complexes_bool, &
    datadist_filename, array_bool, &
    output_complexes_filename, output_complexes_bool, &
    nb_encounters, nb_encounters_bool, &
    cutoff, cutoff_bool, &
    help_bool)

  if (help_bool) then
    call print_help()
    stop 0
  end if

  if (.not. array_input_bool) then
    print *, '[threshold] ERROR: Array input file not given. Use -array_input <file>'
    print *, '[threshold] For usage, run: ./threshold -help'
    stop 1
  end if

  if (.not. complexes_bool) then
    print *, '[threshold] ERROR: Complexes file not provided. Use -complexes <file>'
    print *, '[threshold] For usage, run: ./threshold -help'
    stop 1
  end if

  if (.not. array_bool) then
    print *, '[threshold] ERROR: Array output file not given. Use -array <file>'
    print *, '[threshold] For usage, run: ./threshold -help'
    stop 1
  end if

  if (.not. output_complexes_bool) then
    print *, '[threshold] ERROR: Complexes output file not given. Use -complexes_output <file>'
    print *, '[threshold] For usage, run: ./threshold -help'
    stop 1
  end if

  if (.not. cutoff_bool) then
    print *, '[threshold] ERROR: Cutoff not provided. Use -cutoff <value>'
    print *, '[threshold] For usage, run: ./threshold -help'
    stop 1
  end if

  call read_assoc(complexes, complexes_filename, tot_encounters)
  call read_array(distarray, nb_encounters, array_input_filename)

  if (nb_encounters > size(distarray)) then
    print *, '[threshold] WARNING: -nb_encounters > array size. Using array size.'
    nb_encounters = size(distarray)
  end if

  if (nb_encounters > tot_encounters) then
    print *, '[threshold] WARNING: -nb_encounters > complexes size. Using complexes size.'
    nb_encounters = tot_encounters
  else if (.not. nb_encounters_bool) then
    nb_encounters = min(size(distarray), tot_encounters)
  end if

  allocate(encounter_indexes(nb_encounters))
  do i = 1, nb_encounters
    encounter_indexes(i) = i
  end do

  call sort_array(distarray(1:nb_encounters), encounter_indexes)

  call write_array_cutoff(distarray(1:nb_encounters), datadist_filename, cutoff)

  call write_cutoff_complexes( &
    complexes, distarray(1:nb_encounters), encounter_indexes, &
    nb_encounters, cutoff, output_complexes_filename)

  print *, 'Threshold complete and encounters stored in ', trim(output_complexes_filename)

contains

  !> Parse command-line arguments.
  subroutine parse_arguments( &
    p_array_input_filename, p_array_input_bool, &
    p_complexes_filename, p_complexes_bool, &
    p_datadist_filename, p_array_bool, &
    p_output_complexes_filename, p_output_complexes_bool, &
    p_nb_encounters, p_nb_encounters_bool, &
    p_cutoff, p_cutoff_bool, &
    p_help_bool)

    implicit none

    character(len=128), intent(out) :: p_array_input_filename
    logical, intent(out) :: p_array_input_bool
    character(len=128), intent(out) :: p_complexes_filename
    logical, intent(out) :: p_complexes_bool
    character(len=128), intent(out) :: p_datadist_filename
    logical, intent(out) :: p_array_bool
    character(len=128), intent(out) :: p_output_complexes_filename
    logical, intent(out) :: p_output_complexes_bool
    integer, intent(out) :: p_nb_encounters
    logical, intent(out) :: p_nb_encounters_bool
    real(kind=8), intent(out) :: p_cutoff
    logical, intent(out) :: p_cutoff_bool
    logical, intent(out) :: p_help_bool

    integer :: nb_argument, count_arg, ios
    character(len=128) :: argument

    nb_argument = command_argument_count()

    p_array_input_bool = .false.
    p_complexes_bool = .false.
    p_array_bool = .false.
    p_output_complexes_bool = .false.
    p_nb_encounters_bool = .false.
    p_cutoff_bool = .false.
    p_help_bool = .false.
    p_nb_encounters = 0
    p_cutoff = 0.d0

    if (nb_argument == 0) then
      call print_help()
      stop 1
    end if

    count_arg = 1
    do while (count_arg <= nb_argument)
      call getarg(count_arg, argument)

      if (trim(argument) == '-array_input') then
        p_array_input_bool = .true.
        call getarg(count_arg + 1, argument)
        p_array_input_filename = trim(argument)
        count_arg = count_arg + 1

      else if (trim(argument) == '-complexes') then
        p_complexes_bool = .true.
        call getarg(count_arg + 1, argument)
        p_complexes_filename = trim(argument)
        count_arg = count_arg + 1

      else if (trim(argument) == '-array') then
        p_array_bool = .true.
        call getarg(count_arg + 1, argument)
        p_datadist_filename = trim(argument)
        count_arg = count_arg + 1

      else if (trim(argument) == '-complexes_output') then
        p_output_complexes_bool = .true.
        call getarg(count_arg + 1, argument)
        p_output_complexes_filename = trim(argument)
        count_arg = count_arg + 1

      else if (trim(argument) == '-nb_encounters') then
        p_nb_encounters_bool = .true.
        call getarg(count_arg + 1, argument)
        read(argument, *, iostat=ios) p_nb_encounters
        if (ios /= 0) then
          print *, '[threshold] ERROR: Integer expected for -nb_encounters.'
          stop 1
        end if
        count_arg = count_arg + 1

      else if (trim(argument) == '-cutoff') then
        p_cutoff_bool = .true.
        call getarg(count_arg + 1, argument)
        read(argument, *, iostat=ios) p_cutoff
        if (ios /= 0) then
          print *, '[threshold] ERROR: Real expected for -cutoff.'
          stop 1
        end if
        count_arg = count_arg + 1

      else if (trim(argument) == '-help') then
        p_help_bool = .true.

      else
        print *, '[threshold] ERROR: Argument not recognized: ', trim(argument)
        print *, '[threshold] For usage, run: ./threshold -help'
        stop 1
      end if

      count_arg = count_arg + 1
    end do

  end subroutine parse_arguments

  !> Print usage/help text for threshold.
  subroutine print_help()
    implicit none

    print *, ''
    print *, 'Threshold filters complexes using an array generated by make_data.'
    print *, ''
    print *, 'Required options:'
    print *, '  -array_input <file>      Input array from make_data (-input output)'
    print *, '  -complexes <file>        Complexes file matching array ordering'
    print *, '  -array <file>            Output filtered array file'
    print *, '  -complexes_output <file> Output filtered complexes file'
    print *, '  -cutoff <value>          Threshold cutoff'
    print *, ''
    print *, 'Optional options:'
    print *, '  -nb_encounters <N>       Use first N encounters from input array'
    print *, '  -help'
    print *, ''
    print *, 'Example:'
    print *, '  ./threshold -array_input array_z.txt -complexes assoc_complexes', &
             ' -array threshold_z_array.txt -complexes_output threshold_z.txt', &
             ' -cutoff 6.0'
    print *, ''

  end subroutine print_help

  !> Write selected encounter complexes to an output file.
  subroutine write_cutoff_complexes(complexes_arg, distarray_arg, encounter_indexes_arg, &
                                    nb_encounters_arg, cutoff_arg, output_name_arg)

    implicit none
    type(type_assoc_file), intent(in) :: complexes_arg
    real(kind=8), dimension(:), intent(in) :: distarray_arg
    integer, dimension(:), intent(in) :: encounter_indexes_arg
    integer, intent(in) :: nb_encounters_arg
    real(kind=8), intent(in) :: cutoff_arg
    character(len=*), intent(in) :: output_name_arg

    integer :: idx, unit_number

    unit_number = 15
    open(unit=unit_number, file=output_name_arg, status='replace', action='write')

    do idx = 1, 4
      write(unit_number, '(A)') complexes_arg % head(idx)
    end do

    do idx = 1, nb_encounters_arg
      if (distarray_arg(idx) > cutoff_arg) exit
      write(unit_number, '(A)') complexes_arg % lines(encounter_indexes_arg(idx))
    end do

    close(unit_number)

  end subroutine write_cutoff_complexes

  !> Write array values up to cutoff using F10.4 formatting.
  subroutine write_array_cutoff(array_arg, filename_arg, cutoff_arg)

    implicit none
    real(kind=8), dimension(:), intent(in) :: array_arg
    character(len=*), intent(in) :: filename_arg
    real(kind=8), intent(in) :: cutoff_arg

    integer :: idx, count, nelements, unit_number
    character(len=128) :: fmt

    nelements = size(array_arg)
    count = 0
    unit_number = 16

    do idx = 1, nelements
      if (array_arg(idx) > cutoff_arg) exit
      count = count + 1
    end do

    open(unit_number, file=trim(filename_arg), status='replace', action='write')

    if (count > 0) then
      write(fmt, '(I0, A)') count, 'F10.4'
      fmt = '(' // trim(fmt) // ')'
      write(unit_number, fmt) (array_arg(idx), idx = 1, count)
    else
      write(unit_number, '(A)') ''
    end if

    close(unit_number)

  end subroutine write_array_cutoff

end program main
